variables:
  MINIO_URL: https://minio.retd.edf.fr
  MINIO_MC: ./artf/mc --insecure
  reg_debug: '/.*debug$/'

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_REF_NAME =~ /^maint\/.*/

stages:
  - setup
  - build-singularity
  - build-docker
  - deploy
  - optional

image:
  name: nexus.retd.edf.fr:5012/debian:bookworm

tools:
  stage: setup
  script:
    - env
    - echo "+ $(date) - job ${CI_JOB_NAME} started from $(pwd)"
    - apt-get update
    - apt-get install -y wget
    - echo "+ downloading minIO client..."
    - mkdir artf
    - wget --no-check-certificate -O artf/mc ${MINIO_URL}/codeaster/tools/mc
    - chmod 755 artf/mc
  artifacts:
    paths:
      - artf/mc
    expire_in: 1 day

archive:
  stage: setup
  script:
    - apt-get update
    - apt-get install -y curl git make wget
    - .gitlabci/build_archive.sh
  artifacts:
    paths:
      - artf/archive-oss.tar.gz
    expire_in: 1 day

singularity:
  stage: build-singularity
  rules:
    - if: $CI_COMMIT_REF_NAME !~ $reg_debug
  tags:
    - singularity
  needs: ["tools", "archive"]
  image:
    name: nexus.retd.edf.fr/singularity/singularity:v3.7.3
    entrypoint: ["/bin/sh", "-c"]
  parallel:
    matrix:
      - DISTR: debian-10
      - DISTR: debian-11
      - DISTR: debian-11-oss
      - DISTR: debian-12
      - DISTR: ubuntu-22
      - DISTR: ubuntu-22-oss
  script:
    - .gitlabci/build_singularity.sh ${DISTR} ${CI_COMMIT_REF_NAME} release
  artifacts:
    paths:
      - artf/codeaster-prerequisites-*${DISTR}*.sif
    expire_in: 1 day

docker:
  stage: build-docker
  rules:
    - if: $CI_COMMIT_REF_NAME !~ $reg_debug
  needs: ["tools", "archive"]
  image:
    name: nexus.retd.edf.fr/kaniko-project/executor:debug
    entrypoint: [""]
  parallel:
    matrix:
      - DISTR: debian-10
      - DISTR: debian-11
      - DISTR: debian-11-oss
      - DISTR: debian-12
      - DISTR: ubuntu-22
      - DISTR: ubuntu-22-oss
  script:
    - sh .gitlabci/build_docker.sh ${DISTR} ${CI_COMMIT_REF_NAME} release

docker_codeaster:
  stage: optional
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  needs: ["docker"]
  image:
    name: nexus.retd.edf.fr/kaniko-project/executor:debug
    entrypoint: [""]
  parallel:
    matrix:
      - DISTR: debian-10
      - DISTR: ubuntu-22-oss
  script:
    - sh .gitlabci/build_docker_codeaster.sh ${DISTR} ${CI_COMMIT_REF_NAME}
  allow_failure: true
  artifacts:
    paths:
      - artf/codeaster-main-*.dockerfile
    expire_in: 1 day

singularity-debug:
  stage: build-singularity
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_REF_NAME =~ $reg_debug
  tags:
    - singularity
  needs: ["tools", "archive"]
  image:
    name: nexus.retd.edf.fr/singularity/singularity:v3.7.3
    entrypoint: ["/bin/sh", "-c"]
  parallel:
    matrix:
      - DISTR: debian-11
  script:
    - .gitlabci/build_singularity.sh ${DISTR} ${CI_COMMIT_REF_NAME} debug
  artifacts:
    paths:
      - artf/codeaster-prerequisites-*${DISTR}*.sif
    expire_in: 1 day

upload:
  stage: deploy
  needs:
    - job: tools
    - job: singularity
      optional: true
    - job: singularity-debug
      optional: true
  script:
    - ${MINIO_MC} alias set minio/ ${MINIO_URL} ${MINIO_LOGIN} ${MINIO_PASSWD}
    - echo "+ uploading image..."
    - ${MINIO_MC} cp artf/codeaster-prerequisites-*.sif minio/codeaster/sif/ci/
